#!/usr/bin/env bash
# Keep this renderer in sync with no-phux/phux/scripts/gen-formula.sh.
set -euo pipefail

tag="${1:?usage: gen-phux-formula.sh <tag> <dist-dir> [out-file]}"
dist="${2:?usage: gen-phux-formula.sh <tag> <dist-dir> [out-file]}"
base="https://github.com/no-phux/phux/releases/download/${tag}"

sha() {
  local f="${dist}/phux-${tag}-$1.tar.gz.sha256" digest
  if [ ! -e "$f" ]; then
    return 0
  fi
  if [ ! -f "$f" ] || [ ! -r "$f" ]; then
    echo "error: checksum sidecar is not a readable file: $f" >&2
    return 1
  fi
  read -r digest _ < "$f" || return 1
  if [[ ! "$digest" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: invalid checksum in $f" >&2
    return 1
  fi
  printf '%s\n' "$digest"
}

arm_mac="$(sha aarch64-apple-darwin)"
x86_linux="$(sha x86_64-unknown-linux-gnu)"
arm_linux="$(sha aarch64-unknown-linux-gnu)"

if [ -z "${arm_mac}${x86_linux}${arm_linux}" ]; then
  echo "error: no artifacts found in ${dist} for ${tag}" >&2
  exit 1
fi

primary_target=""
primary_sha=""
if [ -n "$arm_mac" ]; then
  primary_target="aarch64-apple-darwin"
  primary_sha="$arm_mac"
elif [ -n "$x86_linux" ]; then
  primary_target="x86_64-unknown-linux-gnu"
  primary_sha="$x86_linux"
elif [ -n "$arm_linux" ]; then
  primary_target="aarch64-unknown-linux-gnu"
  primary_sha="$arm_linux"
fi

emit() {
  cat <<EOF
# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/no-phux/phux"
  url "${base}/phux-${tag}-${primary_target}.tar.gz"
  sha256 "${primary_sha}"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    url :stable
    strategy :github_latest
  end

EOF

  if [ -z "${x86_linux}${arm_linux}" ]; then
    echo "  depends_on :macos"
    echo ""
  elif [ -z "$arm_mac" ]; then
    echo "  depends_on :linux"
    echo ""
  fi

  if [ -n "$arm_mac" ]; then
    echo "  on_macos do"
    echo "    depends_on arch: :arm64"
    if [ "$primary_target" != "aarch64-apple-darwin" ]; then
      echo "    on_arm do"
      echo "      url \"${base}/phux-${tag}-aarch64-apple-darwin.tar.gz\""
      echo "      sha256 \"${arm_mac}\""
      echo "    end"
    fi
    echo "  end"
    echo ""
  fi

  if [ -n "${x86_linux}${arm_linux}" ]; then
    echo "  on_linux do"
    if [ -z "$arm_linux" ]; then
      echo "    depends_on arch: :x86_64"
    elif [ -z "$x86_linux" ]; then
      echo "    depends_on arch: :arm64"
    fi
    if [ -n "$x86_linux" ] && [ "$primary_target" != "x86_64-unknown-linux-gnu" ]; then
      echo "    on_intel do"
      echo "      url \"${base}/phux-${tag}-x86_64-unknown-linux-gnu.tar.gz\""
      echo "      sha256 \"${x86_linux}\""
      echo "    end"
    fi
    if [ -n "$arm_linux" ] && [ "$primary_target" != "aarch64-unknown-linux-gnu" ]; then
      echo "    on_arm do"
      echo "      url \"${base}/phux-${tag}-aarch64-unknown-linux-gnu.tar.gz\""
      echo "      sha256 \"${arm_linux}\""
      echo "    end"
    fi
    echo "  end"
    echo ""
  fi

  cat <<'EOF'
  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_path_exists bin/"phux-mcp"
    assert_predicate bin/"phux-mcp", :executable?
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
EOF
}

out="${3:-}"
if [ -n "$out" ]; then
  emit > "$out"
  echo "wrote $out" >&2
else
  emit
fi
