# This file was generated by GoReleaser. DO NOT EDIT.
cask "phbv" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "cfb397d485a6fab6f0de5acef987b4c3ad1d09f3527992c25ddd2dddbfc76030"
      url "https://github.com/phall1/phbv/releases/download/v#{version}/phbv_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d88df9efd9d3d5552d3d6751bc0f683be918af45f1c8e63bbdeee2d71dae1bd"
      url "https://github.com/phall1/phbv/releases/download/v#{version}/phbv_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d43b768c4506c298118a1e24858aa4fb3228ade796f5d7125b8516c94f894f65"
      url "https://github.com/phall1/phbv/releases/download/v#{version}/phbv_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbeb658cedfbb7968913ec585d684887070dd13892b9f27347acd1df7ef55199"
      url "https://github.com/phall1/phbv/releases/download/v#{version}/phbv_linux_arm64.tar.gz"
    end
  end

  name "phbv"
  desc "Terminal UI for beads (bd) issue tracking"
  homepage "https://github.com/phall1/phbv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phbv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phbv"]
    end
  end

  # No zap stanza required

end
