# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/phall1/phux"
  url "https://github.com/phall1/phux/releases/download/v0.17.0/phux-v0.17.0-aarch64-apple-darwin.tar.gz"
  sha256 "8122dc96a2e3aa305fd57875bd91216257d63968b0e889bfbd166d89ddb2dfef"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    depends_on arch: :arm64
  end

  on_linux do
    on_intel do
      url "https://github.com/phall1/phux/releases/download/v0.17.0/phux-v0.17.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a4c94a72e4a73451f98a455c2bd46ea100ee501c58d29972741dae0a9448c4fc"
    end
    on_arm do
      url "https://github.com/phall1/phux/releases/download/v0.17.0/phux-v0.17.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "615b69a01306a497164fb24e9ea21855f850e5695301bc53febb2a7def18d6d2"
    end
  end

  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_path_exists bin/"phux-mcp"
    assert_predicate bin/"phux-mcp", :executable?
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
