# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/no-phux/phux"
  url "https://github.com/no-phux/phux/releases/download/v0.24.0/phux-v0.24.0-aarch64-apple-darwin.tar.gz"
  sha256 "1a28cc35742eccc96e7f8cdfab3c8a2560d62f4daead853d8ecab9e49c8c1b2b"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    depends_on arch: :arm64
  end

  on_linux do
    on_intel do
      url "https://github.com/no-phux/phux/releases/download/v0.24.0/phux-v0.24.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fd874fe275d0e6dc78d9afc9c4df5634a6146da076339105e846505086e2557d"
    end
    on_arm do
      url "https://github.com/no-phux/phux/releases/download/v0.24.0/phux-v0.24.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2ec89ec8c20d01e48df323d7bc6cd3ff9c10ee5cb37e209789dec3cec9db3fd9"
    end
  end

  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_path_exists bin/"phux-mcp"
    assert_predicate bin/"phux-mcp", :executable?
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
