# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/no-phux/phux"
  url "https://github.com/no-phux/phux/releases/download/v0.25.0/phux-v0.25.0-aarch64-apple-darwin.tar.gz"
  sha256 "4a4a8c46e760ce66dec38c8bb7975974564d52b7c7d31e062bcb2a5c7841102b"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    depends_on arch: :arm64
  end

  on_linux do
    on_intel do
      url "https://github.com/no-phux/phux/releases/download/v0.25.0/phux-v0.25.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "54b53499ad2f25827ce45e1191cc22ffaf8fd841045a11226f91f33a43a77c51"
    end
    on_arm do
      url "https://github.com/no-phux/phux/releases/download/v0.25.0/phux-v0.25.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e6e576a7b299a4b0966544765e99229189eed314359493b122944b3ed448b635"
    end
  end

  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_path_exists bin/"phux-mcp"
    assert_predicate bin/"phux-mcp", :executable?
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
